apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: backend-destination
  namespace: httpbin
spec:
  host: backend
  subsets:
  - name: stable
    labels:
      app: backend
      version: v1
  - name: canary
    labels:
      app: backend
      version: v2