apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: backend-vs
  namespace: httpbin
spec:
  hosts:
  - 'backend'
  http:
  - route:
    - destination:
        host: backend
        subset: stable
      weight: 50
    - destination:
        host: backend
        subset: canary
      weight: 50
 


