apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
    app.kubernetes.io/instance: httpbin
  name: backend
  namespace: httpbin
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
status:
  loadBalancer: {}
