apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
spec:
  destination:
    namespace: httpbin
    server: https://kubernetes.default.svc 
  project: default 
  source:
    repoURL: https://github.com/younes-bami/httpbin.git
    path: kustomize/base/backend
    directory: 
      recurse: true
    #targetRevision: minikube
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false