---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1
  namespace: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      metadata:
      #annotations:                                                                                       
      #  sidecar.istio.io/userVolumeMount: '[{"name":"nginx-client-certs", "mountPath":"/etc/istio/nginx-client-certs", "readonly":true},{"name":"nginx-ca-certs", "mountPath":"/etc/istio/nginx-ca-certs", "readonly":true}]'
      #  sidecar.istio.io/userVolume: '[{"name":"nginx-client-certs", "secret":{"secretName":"nginx-client-certs"}},{"name":"nginx-ca-certs", "secret":{"secretName":"nginx-ca-certs"}}]'
      labels:
        app: backend
        version: v1
    spec:
      selector:
        matchLabels:
          app: backend
          version: v1
      strategy: {}
      containers:
      - env:
        - name: APP_BACKEND
          value: http://ec2-34-251-198-112.eu-west-1.compute.amazonaws.com/status/200
        - name: APP_VERSION
          value: v1
        - name: quarkus.log.console.color
          value: "false"
        image: quay.io/voravitl/backend-native:v1
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 120Mi
          requests:
            cpu: 50m
            memory: 40Mi