apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: httpbin-rollout
spec:
  replicas: 1
  strategy:
    canary:
      steps:
      - setWeight: 5
      - pause: 
          duration: 60
      - setWeight: 10
      - pause:
          duration: 60
      - setWeight: 25
      - pause: 
          duration: 60
      - setWeight: 50
      - pause:
          duration: 60
      - setWeight: 100
      - pause: {}
      trafficRouting:
        istio:
          destinationRule:
            canarySubsetName: canary
            name: backend-destination
            stableSubsetName: stable
          virtualService:
            name: backend-vs
            routes:
            - primary
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        istio-injection: enabled
    spec:
      containers:
      - name: backend
        image: younesic/httpbin:v1
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m