apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: httpbin-rollout
spec:
  replicas: 1
  strategy:
    canary:
      steps:
      - setWeight: 5
      - pause: 
          duration: 60
      - setWeight: 10
      - pause:
          duration: 60
      - setWeight: 25
      - pause: 
          duration: 60
      - setWeight: 50
      - pause:
          duration: 60
      - setWeight: 100
      - pause: {}
      trafficRouting:
        istio:
          destinationRule:
            canarySubsetName: canary
            name: backend-destination
            stableSubsetName: stable
          virtualService:
            name: backend-vs
            routes:
            - primary
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        istio-injection: enabled
    spec:
      containers:
      - env:
        - name: APP_BACKEND
          value: http://ec2-34-251-198-112.eu-west-1.compute.amazonaws.com/status/200
        - name: APP_VERSION
          value: v2
        - name: quarkus.log.console.color
          value: "false"
        image: quay.io/voravitl/backend-native:v1
        name: backend
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m